version: '3'

services:
  node:
    build:
      context: .
    container_name: node
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s /usr/local/bin/docker-entrypoint.sh
    command: node /usr/src/app/index.js
    tty: true
    depends_on:
      - mysql
    networks:
      - node-network

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=challengenode
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    image: nginx:1.15.0
    container_name: nginx
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge